services:
  outubro-rosa-banpara:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: banpara-outubro-rosa
    restart: unless-stopped
    ports:
      # Porta 8090 mapeada para evitar conflito com outros serviços (como 80, 8080 e 3000)
      - "8090:80"
    environment:
      - TZ=America/Belem
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
